"""Build and check the seven-language X profile directory. Python 3.11+, stdlib only."""
from __future__ import annotations

import argparse
import csv
import hashlib
import html
import io
import json
import posixpath
import re
from collections import Counter
from datetime import date, datetime, timezone
from pathlib import Path
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
LOCALES = {"en": "English", "zh-CN": "简体中文", "ko": "한국어", "ja": "日本語",
           "ru": "Русский", "fr": "Français", "es": "Español"}
PUBLIC_DOCS = (
    "CONTRIBUTING.md", "CODE_OF_CONDUCT.md", "SECURITY.md", "SUPPORT.md", "CHANGELOG.md",
    "docs/curation-policy.md", "docs/ai-workflow.md", "docs/maintenance.md", "docs/research-backlog.md",
)
GENERATED = "<!-- Generated by scripts/catalog.py. Edit data, locales, or templates. -->\n"
TOKEN = re.compile(r"\{\{([A-Z_]+)\}\}")
COMMANDS = (chr(96)*3 + "sh\npython scripts/catalog.py build\npython scripts/catalog.py check\n"
            "python -m unittest discover -s tests -v\ngit diff --check\n" + chr(96)*3)
BRANCH_COMMANDS = (chr(96)*3 + "sh\ngit clone https://github.com/YOUR_USERNAME/awesome-ai-x-accounts.git\n"
                   "cd awesome-ai-x-accounts\ngit switch -c add/ACCOUNT_HANDLE\n" + chr(96)*3)
SUBMIT_COMMANDS = (chr(96)*3 + "sh\ngit add data/accounts.json data/accounts.csv data/handles.txt "
                   "data/research-backlog.json "
                   "'README*.md' 'assets/stats*.svg'\ngit commit -m \"feat(data): add ACCOUNT_HANDLE\"\n"
                   "git push -u origin add/ACCOUNT_HANDLE\n" + chr(96)*3)


class CatalogError(ValueError):
    """An actionable data or generation error."""


def require(condition: bool, message: str) -> None:
    if not condition:
        raise CatalogError(message)


def digest(value: object) -> str:
    return hashlib.sha256(json.dumps(value, ensure_ascii=False, sort_keys=True,
                                     separators=(",", ":")).encode("utf-8")).hexdigest()


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def validate_shape(value: object, schema: dict, path: str = "$") -> None:
    types = {"object": dict, "array": list, "string": str, "integer": int, "null": type(None)}
    expected = schema.get("type")
    if expected:
        allowed = expected if isinstance(expected, list) else [expected]
        require(any(type(value) is types[k] for k in allowed), f"{path}: expected {expected}")
    if "enum" in schema:
        require(value in schema["enum"], f"{path}: invalid value")
    if value is None:
        return
    if isinstance(value, dict):
        require(not set(schema.get("required", [])) - value.keys(), f"{path}: missing field")
        properties = schema.get("properties", {})
        if schema.get("additionalProperties") is False:
            require(not value.keys() - properties.keys(), f"{path}: unknown field")
        for key in value.keys() & properties.keys():
            validate_shape(value[key], properties[key], f"{path}.{key}")
    elif isinstance(value, list):
        require(len(value) >= schema.get("minItems", 0), f"{path}: too few items")
        for index, item in enumerate(value):
            validate_shape(item, schema.get("items", {}), f"{path}[{index}]")
    elif isinstance(value, str):
        require(len(value) >= schema.get("minLength", 0), f"{path}: too short")
        require(len(value) <= schema.get("maxLength", len(value)), f"{path}: too long")
        multiline = schema.get("x-verbatim", False)
        require(not any(ord(c) < 32 and not (multiline and c in "\n\r\t") for c in value),
                f"{path}: control character")
        if not multiline:
            require(value == value.strip(), f"{path}: surrounding whitespace")
        if "pattern" in schema:
            require(re.fullmatch(schema["pattern"], value) is not None, f"{path}: invalid format")
        if schema.get("format") == "date":
            try:
                parsed = date.fromisoformat(value)
            except ValueError as exc:
                raise CatalogError(f"{path}: invalid date") from exc
            require(parsed.isoformat() == value and parsed <= date.today(), f"{path}: invalid or future date")
        if schema.get("format") == "date-time":
            try:
                parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
            except ValueError as exc:
                raise CatalogError(f"{path}: invalid timestamp") from exc
            require(parsed.tzinfo is not None, f"{path}: timestamp needs timezone")
            require(parsed <= datetime.now(timezone.utc), f"{path}: future timestamp")
    elif type(value) is int:
        require(value >= schema.get("minimum", value), f"{path}: below minimum")


def validate(data: dict, schema: dict) -> None:
    validate_shape(data, schema)
    categories = [c["id"] for c in data["categories"]]
    require(len(categories) == len(set(categories)), "duplicate category")
    handles, ids = set(), set()
    for account in data["accounts"]:
        handle = account["handle"]
        require(handle.lower() not in handles, f"duplicate handle: {handle}")
        require(account["id"] not in ids, f"duplicate numeric account id: {account['id']}")
        handles.add(handle.lower())
        ids.add(account["id"])
        require(account["category"] in categories, f"{handle}: unknown category")
        require(account["url"] == f"https://x.com/{handle}", f"{handle}: URL mismatch")
        source = urlsplit(account["source_url"])
        require(source.scheme == "https" and source.hostname in {"x.com", "api.fxtwitter.com"}
                and not source.username and not source.password and not source.query and not source.fragment,
                f"{handle}: invalid profile source")
        prefix = "/" if source.hostname == "x.com" else "/2/profile/"
        require(source.path.startswith(prefix) and source.path[len(prefix):].lower() == handle.lower(),
                f"{handle}: source handle mismatch")


def load_catalog(root: Path = ROOT) -> tuple[dict, dict]:
    return read_json(root / "data/accounts.json"), read_json(root / "data/accounts.schema.json")


def load_locales(root: Path = ROOT) -> dict:
    return {p.stem: read_json(p) for p in sorted((root / "locales").glob("*.json"))}


def load_backlog(root: Path = ROOT) -> dict:
    return read_json(root / "data/research-backlog.json")


def validate_translation_shape(value: object, reference: object, path: str) -> None:
    require(type(value) is type(reference), f"{path}: translation type mismatch")
    if isinstance(reference, dict):
        require(value.keys() == reference.keys(), f"{path}: missing or extra translation keys")
        for key in reference:
            validate_translation_shape(value[key], reference[key], f"{path}.{key}")
    elif isinstance(reference, list):
        require(len(value) == len(reference), f"{path}: translation list length mismatch")
        for index, (item, original) in enumerate(zip(value, reference)):
            validate_translation_shape(item, original, f"{path}[{index}]")
    else:
        require(isinstance(value, str) and bool(value.strip()), f"{path}: empty translation")
        require(value == value.strip() and "\r" not in value, f"{path}: noncanonical whitespace")
        require(Counter(TOKEN.findall(value)) == Counter(TOKEN.findall(reference)),
                f"{path}: translation placeholder mismatch")


def validate_locales(data: dict, locales: dict, backlog: dict) -> None:
    require(locales.keys() == LOCALES.keys(), "missing or extra locale")
    english = locales["en"]
    require(english.keys() == {"ui", "docs"}, "en: unknown fields")
    require(english["docs"].keys() == set(PUBLIC_DOCS), "en: missing or extra public documents")
    validate_translation_shape(english, english, "en")
    require(english["ui"]["categories"] == {c["id"]: c["title"] for c in data["categories"]},
            "English categories differ from canonical data")
    for key, length in {"stats": 3, "exports": 3, "issue": 8, "correction": 6,
                        "backlog_headers": 2}.items():
        require(len(english["ui"][key]) == length, f"en.ui.{key}: invalid list length")
    for locale in LOCALES:
        if locale == "en":
            continue
        resource = locales[locale]
        require(resource.keys() == {"ui", "docs", "source_digest"}, f"{locale}: unknown locale fields")
        require(resource["source_digest"] == digest(english), f"{locale}: stale interface/document translation")
        for key in ("ui", "docs"):
            validate_translation_shape(resource[key], english[key], f"{locale}.{key}")
    require(backlog.keys() == {"research_date", "candidates"}, "invalid backlog fields")
    validate_shape(backlog["research_date"], {"type": "string", "format": "date"}, "backlog.research_date")
    handles = []
    for candidate in backlog["candidates"]:
        require(candidate.keys() == {"name", "handle"}, "invalid backlog candidate fields")
        validate_shape(candidate["name"], {"type": "string", "minLength": 1}, "backlog.name")
        validate_shape(candidate["handle"], {"type": "string", "pattern": "[A-Za-z0-9_]{1,15}"}, "backlog.handle")
        handles.append(candidate["handle"].lower())
    require(len(handles) == len(set(handles)), "duplicate backlog candidate")
    require(not set(handles) & {a["handle"].lower() for a in data["accounts"]},
            "backlog candidate already published")


def md(value: str) -> str:
    escaped = html.escape(value, quote=False)
    special = set("\\|[]*_") | {chr(96)}
    return "".join("\\" + c if c in special else c for c in escaped)


def bio_markdown(value: str | None) -> str:
    if value is None or value == "":
        return "—"
    # Preserve wording and line breaks; do not interpret profile text as Markdown/HTML.
    return md(value).replace("\r\n", "\n").replace("\r", "\n").replace("\n", "<br />").replace("\t", "&#9;")


def csv_safe(value: str) -> str:
    return "'" + value if value.lstrip().startswith(("=", "+", "-", "@")) or value.startswith(("\t", "\r")) else value


def localized_path(path: str, locale: str) -> str:
    if locale == "en":
        return path
    parent, name = posixpath.split(path)
    if parent == "docs":
        return f"docs/{locale}/{name}"
    stem, extension = posixpath.splitext(name)
    return posixpath.join(parent, f"{stem}.{locale}{extension}")


def relative_link(page: str, target: str) -> str:
    return posixpath.relpath(target, posixpath.dirname(page) or ".")


def language_nav(document: str, locale: str) -> str:
    page = localized_path(document, locale)
    return " · ".join(f"**{name}**" if lang == locale else
                      f"[{name}]({relative_link(page, localized_path(document, lang))})"
                      for lang, name in LOCALES.items())


def substitute(text: str, values: dict[str, str]) -> str:
    def replace(match: re.Match) -> str:
        require(match[1] in values, f"unknown placeholder: {match[1]}")
        return values[match[1]]
    return TOKEN.sub(replace, text)


def context(document: str, locale: str) -> dict[str, str]:
    page = localized_path(document, locale)
    targets = {
        "POLICY_LINK": "docs/curation-policy.md", "COC_LINK": "CODE_OF_CONDUCT.md",
        "BACKLOG_LINK": "docs/research-backlog.md", "MAINTENANCE_LINK": "docs/maintenance.md",
        "WORKFLOW_LINK": "docs/ai-workflow.md", "CONTRIBUTING_LINK": "CONTRIBUTING.md",
        "CHANGELOG_LINK": "CHANGELOG.md", "SUPPORT_LINK": "SUPPORT.md", "SECURITY_LINK": "SECURITY.md",
    }
    values = {key: relative_link(page, localized_path(target, locale)) for key, target in targets.items()}
    values.update({
        "LICENSE_LINK": relative_link(page, "LICENSE"), "AGENTS_LINK": relative_link(page, "AGENTS.md"),
        "COMMANDS": COMMANDS, "BRANCH_COMMANDS": BRANCH_COMMANDS, "SUBMIT_COMMANDS": SUBMIT_COMMANDS,
        "FETCH_COMMAND": chr(96)*3 + "sh\npython scripts/fetch_profiles.py ACCOUNT_HANDLE --category research --output .tmp/account.json\n" + chr(96)*3,
    })
    for key, name in (("ISSUE_URL", "account.yml"), ("CORRECTION_URL", "correction.yml")):
        values[key] = ("https://github.com/everclear077/awesome-ai-x-accounts/issues/new?template="
                       + localized_path(name, locale))
    return values


def stats_svg(total: int, categories: int, labels: list[str]) -> str:
    numbers = [total, categories, len(LOCALES)]
    title = " · ".join(f"{number} {label}" for number, label in zip(numbers, labels))
    pieces = [
        '<svg xmlns="http://www.w3.org/2000/svg" width="950" height="112" viewBox="0 0 950 112" role="img" aria-labelledby="title">',
        f'<title id="title">{html.escape(title)}</title>',
        '<rect x="1" y="1" width="948" height="110" rx="18" fill="#101d31" stroke="#283b54"/>',
        '<g font-family="Arial, sans-serif" text-anchor="middle">',
    ]
    for index, (number, label) in enumerate(zip(numbers, labels)):
        x = 158 + index * 317
        pieces += [f'<text x="{x}" y="53" font-size="32" font-weight="700" fill="#76e6d4">{number}</text>',
                   f'<text x="{x}" y="81" font-size="12" fill="#b6c7dd">{html.escape(label)}</text>']
        if index:
            pieces.append(f'<path d="M{index * 317} 28v56" stroke="#283b54"/>')
    return "\n".join(pieces + ["</g>", "</svg>", ""])


def issue_form(ui: dict, locale: str, correction: bool = False) -> str:
    terms = ui["correction" if correction else "issue"]
    quote = lambda value: json.dumps(value, ensure_ascii=False)
    pieces = [f"name: {quote(LOCALES[locale] + ' · ' + terms[0])}",
              f"description: {quote(terms[1])}",
              f"title: {quote('[Correction] ' if correction else '[Account] ')}", "body:"]
    fields = [("input", "url", terms[2], True)]
    if correction:
        fields += [("textarea", "change", terms[3], True),
                   ("textarea", "snapshot", terms[4], False), ("textarea", "context", terms[5], False)]
    else:
        fields += [("input", "category", terms[3], True), ("textarea", "bio", terms[4], False),
                   ("input", "followers", terms[5], False), ("input", "observed_at", terms[6], False),
                   ("textarea", "context", terms[7], False)]
    for kind, identifier, label, required in fields:
        pieces += [f"  - type: {kind}", f"    id: {identifier}", "    attributes:", f"      label: {quote(label)}",
                   "    validations:", f"      required: {str(required).lower()}"]
    return "\n".join(pieces) + "\n"


def generate(data: dict, template: str, locales: dict, backlog: dict) -> dict[str, str]:
    accounts = sorted(data["accounts"], key=lambda a: a["handle"].lower())
    counts = Counter(a["category"] for a in accounts)
    quantities = {"COUNT": str(len(accounts)), "CATEGORY_COUNT": str(len(data["categories"])),
                  "LANGUAGE_COUNT": str(len(LOCALES)),
                  "SNAPSHOT_DATE": max(a["observed_at"][:10] for a in accounts)}
    output = io.StringIO(newline="")
    fields = ["id", "handle", "name", "url", "category", "bio", "followers_count", "observed_at", "source_url"]
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow(fields)
    for account in accounts:
        writer.writerow([csv_safe("" if account[key] is None else str(account[key])) for key in fields])
    outputs = {"data/handles.txt": "\n".join(a["handle"] for a in accounts) + "\n",
               "data/accounts.csv": "\ufeff" + output.getvalue()}
    for locale in LOCALES:
        ui = locales[locale]["ui"]
        values = context("README.md", locale) | quantities
        values.update({key.upper(): substitute(value, values) for key, value in ui.items() if isinstance(value, str)})
        directory = [f'| {ui["topic"]} | {ui["count"]} |', "| --- | ---: |"]
        sections = []
        for category in data["categories"]:
            cid = category["id"]
            title = md(ui["categories"][cid])
            directory.append(f"| [{title}](#{cid}) | {counts[cid]} |")
            sections += [f'<a id="{cid}"></a>', "", f"## {title}", "",
                         f'| {ui["account"]} | {ui["bio"]} | {ui["followers"]} |',
                         "| --- | --- | ---: |"]
            for account in accounts:
                if account["category"] != cid:
                    continue
                identity = f'**{bio_markdown(account["name"])}**<br />[@{md(account["handle"])}]({account["url"]})'
                followers = "—" if account["followers_count"] is None else f'{account["followers_count"]:,}'
                sections.append(f'| {identity} | {bio_markdown(account["bio"])} | {followers} |')
            sections += ["", f'[↑ {ui["back"]}](#directory)', ""]
        exports = [f'| {ui["format"]} | {ui["use"]} |', "| --- | --- |"]
        for (label, path), description in zip(
            [("JSON", "data/accounts.json"), ("CSV", "data/accounts.csv"), ("TXT", "data/handles.txt")],
            ui["exports"],
        ):
            exports.append(f"| [{label}]({path}) | {md(description)} |")
        values.update({
            "LANGUAGE_NAV": language_nav("README.md", locale),
            "STATS_PATH": localized_path("assets/stats.svg", locale),
            "STATS_ALT": html.escape(" · ".join(f"{number} {label}" for number, label in zip(
                [len(accounts), len(data["categories"]), len(LOCALES)], ui["stats"])), quote=True),
            "DIRECTORY_TABLE": "\n".join(directory), "ACCOUNTS": "\n".join(sections).rstrip(),
            "EXPORT_TABLE": "\n".join(exports),
        })
        outputs[localized_path("README.md", locale)] = substitute(template, values).rstrip() + "\n"
        outputs[localized_path("assets/stats.svg", locale)] = stats_svg(len(accounts), len(data["categories"]), ui["stats"])
        for document in PUBLIC_DOCS:
            page = localized_path(document, locale)
            doc_values = context(document, locale)
            rows = ["| " + " | ".join(ui["backlog_headers"]) + " |", "| --- | --- |"]
            for candidate in sorted(backlog["candidates"], key=lambda a: a["handle"].lower()):
                rows.append(f'| {md(candidate["name"])} | {md(candidate["handle"])} |')
            doc_values.update({"BACKLOG_TABLE": "\n".join(rows), "BACKLOG_DATE": backlog["research_date"]})
            outputs[page] = (GENERATED + "\n" + language_nav(document, locale) + "\n\n"
                             + substitute(locales[locale]["docs"][document], doc_values).rstrip() + "\n")
        for name, correction in (("account.yml", False), ("correction.yml", True)):
            outputs[".github/ISSUE_TEMPLATE/" + localized_path(name, locale)] = issue_form(ui, locale, correction)
    return outputs


def check_local_links(root: Path, rendered: dict[str, str]) -> None:
    texts = dict(rendered)
    for path in root.rglob("*.md"):
        if any(p.startswith(".") or p == "templates" for p in path.relative_to(root).parts[:-1]):
            continue
        texts.setdefault(path.relative_to(root).as_posix(), path.read_text(encoding="utf-8"))
    for pattern in (".github/*.md", ".cursor/rules/*.mdc", ".windsurf/rules/*.md", ".clinerules/*.md"):
        for path in root.glob(pattern):
            texts.setdefault(path.relative_to(root).as_posix(), path.read_text(encoding="utf-8"))
    for filename, content in texts.items():
        if not filename.endswith((".md", ".mdc")):
            continue
        destinations = re.findall(r"!?\[[^\n]*?\]\(([^)\s]+)\)", content)
        destinations += re.findall(r'(?:src|href)="([^"]+)"', content)
        for target in destinations:
            parsed = urlsplit(target)
            if parsed.scheme or parsed.netloc:
                continue
            relative = unquote(parsed.path)
            path = ((root / filename).parent / relative).resolve() if relative else root / filename
            require(path.is_relative_to(root.resolve()), f"{filename}: link escapes repository")
            key = path.relative_to(root.resolve()).as_posix()
            require(key in rendered or path.is_file(), f"{filename}: missing link target {target}")
            if parsed.fragment:
                body = texts.get(key)
                if body is None and path.is_file():
                    body = path.read_text(encoding="utf-8")
                require(body is not None and f'id="{unquote(parsed.fragment)}"' in body,
                        f"{filename}: missing anchor {target}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["build", "check", "digests"])
    args = parser.parse_args()
    try:
        data, schema = load_catalog()
        validate(data, schema)
        locales, backlog = load_locales(), load_backlog()
        if args.command == "digests":
            print(json.dumps({"interface_and_documents": digest(locales["en"])}, indent=2))
            return 0
        validate_locales(data, locales, backlog)
        outputs = generate(data, (ROOT / "templates/README.md").read_text(encoding="utf-8"), locales, backlog)
        check_local_links(ROOT, outputs)
        stale = []
        for filename, content in outputs.items():
            path = ROOT / filename
            if args.command == "build":
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")
            elif not path.is_file() or path.read_bytes() != content.encode("utf-8"):
                stale.append(filename)
        require(not stale, "generated files are stale: " + ", ".join(stale) + "; run python scripts/catalog.py build")
        print(f'{args.command}: OK ({len(data["accounts"])} accounts, {len(data["categories"])} categories, '
              f'{len(LOCALES)} languages, {len(outputs)} generated files)')
        return 0
    except (CatalogError, OSError, ValueError, KeyError) as exc:
        parser.exit(1, f"catalog: {exc}\n")


if __name__ == "__main__":
    raise SystemExit(main())
